Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,7 +4,7 @@
 #
 # For more information, see https://github.com/haskell-CI/haskell-ci
 #
-# version: 0.9.20200125
+# version: 0.9.20200326
 #
 version: ~> 1.0
 language: c
@@ -76,7 +76,6 @@ jobs:
       os: linux
   allow_failures:
     - compiler: ghc-head
-    - compiler: ghc-8.10.1
 before_install:
   - |
     if echo $CC | grep -q ghcjs; then
@@ -104,7 +103,7 @@ before_install:
   - BENCH=--enable-benchmarks
   - if ! $GHCJS && [ $HCNUMVER -lt 70400 ] ; then BENCH=--disable-benchmarks ; fi
   - HEADHACKAGE=false
-  - if ! $GHCJS && [ $HCNUMVER -ge 81000 ] ; then HEADHACKAGE=true ; fi
+  - if ! $GHCJS && [ $HCNUMVER -gt 81001 ] ; then HEADHACKAGE=true ; fi
   - rm -f $CABALHOME/config
   - |
     echo "verbose: normal +nowrap +markoutput"          >> $CABALHOME/config
@@ -144,13 +143,15 @@ install:
   - cat $CABALHOME/config
   - rm -fv cabal.project cabal.project.local cabal.project.freeze
   - travis_retry ${CABAL} v2-update -v
-  - if ! $GHCJS && [ $HCNUMVER -ge 80000 ] ; then (cd /tmp && ${CABAL} v2-install $WITHCOMPILER -j2 doctest --constraint='doctest ==0.16.2.*') ; fi
+  - if ! $GHCJS && [ $HCNUMVER -ge 80000 ] && [ $HCNUMVER -lt 81000 ] ; then (cd /tmp && ${CABAL} v2-install $WITHCOMPILER -j2 doctest --constraint='doctest ==0.16.2.*') ; fi
   - if $GHCJS ; then (cd /tmp && ${CABAL} v2-install -w ghc-8.4.4 cabal-plan --constraint='cabal-plan ^>=0.6.0.0' --constraint='cabal-plan +exe') ; fi
   # Generate cabal.project
   - rm -rf cabal.project cabal.project.local cabal.project.freeze
   - touch cabal.project
   - |
     echo "packages: ." >> cabal.project
+  - if $GHCJS || ! $GHCJS && [ $HCNUMVER -ge 80000 ] ; then echo 'package splitmix' >> cabal.project ; fi
+  - "if $GHCJS || ! $GHCJS && [ $HCNUMVER -ge 80000 ] ; then echo '  ghc-options: -Werror=missing-methods' >> cabal.project ; fi"
   - |
   - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(splitmix)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
@@ -159,8 +160,8 @@ install:
   - ${CABAL} v2-freeze $WITHCOMPILER ${TEST} ${BENCH}
   - "cat cabal.project.freeze | sed -E 's/^(constraints: *| *)//' | sed 's/any.//'"
   - rm  cabal.project.freeze
-  - ${CABAL} v2-build $WITHCOMPILER ${TEST} ${BENCH} --dep -j2 all
-  - ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks --dep -j2 all
+  - travis_wait 40 ${CABAL} v2-build $WITHCOMPILER ${TEST} ${BENCH} --dep -j2 all
+  - travis_wait 40 ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks --dep -j2 all
 script:
   - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
   # Packaging...
@@ -176,6 +177,8 @@ script:
   - touch cabal.project
   - |
     echo "packages: ${PKGDIR_splitmix}" >> cabal.project
+  - if $GHCJS || ! $GHCJS && [ $HCNUMVER -ge 80000 ] ; then echo 'package splitmix' >> cabal.project ; fi
+  - "if $GHCJS || ! $GHCJS && [ $HCNUMVER -ge 80000 ] ; then echo '  ghc-options: -Werror=missing-methods' >> cabal.project ; fi"
   - |
   - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(splitmix)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
@@ -196,7 +199,7 @@ script:
   - if ! $GHCJS ; then ${CABAL} v2-test $WITHCOMPILER ${TEST} ${BENCH} all ; fi
   - if $GHCJS ; then cabal-plan list-bins '*:test:*' | while read -r line; do testpkg=$(echo "$line" | perl -pe 's/:.*//'); testexe=$(echo "$line" | awk '{ print $2 }'); echo "testing $textexe in package $textpkg"; (cd "$(pkgdir $testpkg)" && nodejs "$testexe".jsexe/all.js); done ; fi
   # Doctest...
-  - if ! $GHCJS && [ $HCNUMVER -ge 80000 ] ; then (cd ${PKGDIR_splitmix} && doctest  src src-compat) ; fi
+  - if ! $GHCJS && [ $HCNUMVER -ge 80000 ] && [ $HCNUMVER -lt 81000 ] ; then (cd ${PKGDIR_splitmix} && doctest  src src-compat) ; fi
   # cabal check...
   - (cd ${PKGDIR_splitmix} && ${CABAL} -vnormal check)
   # haddock...
@@ -209,5 +212,5 @@ script:
   # Constraint set no-random
   - ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks --constraint='splitmix -random' all
 
-# REGENDATA ("0.9.20200125",["--config=cabal.haskell-ci","splitmix.cabal"])
+# REGENDATA ("0.9.20200326",["--config=cabal.haskell-ci","splitmix.cabal"])
 # EOF
